create table public.clubs_stage_raw (
  "Club Name" text null,
  links text null,
  "Leadership" double precision null,
  "Teamwork" double precision null,
  "Community Service" double precision null,
  "Advocacy" double precision null,
  "Social Justice" double precision null,
  "Architecture & Urban Planning" double precision null,
  "Technology" double precision null,
  "Arts & Crafts" double precision null,
  "Performing Arts" double precision null,
  "Cultural Expression" double precision null,
  "Diversity & Inclusion" double precision null,
  "Mentorship" double precision null,
  "Career Growth" double precision null,
  "Networking" double precision null,
  "Entrepreneurship" double precision null,
  "Research" double precision null,
  "Fitness" double precision null,
  "Competitive Sports" double precision null,
  "Outdoor Activities" double precision null,
  "Wellness" double precision null,
  "Mental Health" double precision null,
  "Academic Focus" double precision null,
  "Debate & Discussion" double precision null,
  "Virtual Reality" double precision null,
  "Social Events" double precision null,
  "Media & Film" double precision null,
  "Journalism" double precision null,
  "Music" double precision null,
  "Dance" double precision null,
  "UI Design" double precision null,
  "Hospitality" double precision null,
  "International Relations" double precision null,
  "Political Action" double precision null,
  "Fundraising" double precision null,
  "Tutoring & Teaching" double precision null,
  "DIY & Making" double precision null,
  "Ethics" double precision null,
  "Professional Skills" double precision null,
  "Public Speaking" double precision null,
  "Problem Solving" double precision null,
  "Analytics" double precision null,
  "Robotics & AI" double precision null,
  "Space & Astronomy" double precision null,
  "Gaming & eSports" double precision null,
  woman women double precision null,
  man men double precision null,
  lgbtq double precision null,
  "White European Italian" double precision null,
  "Black African American" double precision null,
  "Native American" double precision null,
  "Asian" double precision null,
  "Hispanic" double precision null,
  "Native Hawaiian or Other Pacific Islander" double precision null,
  "Greek" double precision null,
  "Christian" double precision null,
  "Islam" double precision null,
  "Jewish Community and Judaism" double precision null,
  "Hindu" double precision null,
  "Buddhism" double precision null,
  "Sikh" double precision null,
  "Aerospace Engineering" double precision null,
  "Agricultural Business" double precision null,
  "Agricultural Communication" double precision null,
  "Agricultural Science" double precision null,
  "Agricultural Systems Management" double precision null,
  "Animal Science" double precision null,
  "Anthropology and Geography" double precision null,
  "Architectural Engineering" double precision null,
  "Architecture" double precision null,
  "Art and Design" double precision null,
  "Biochemistry" double precision null,
  "Biological Sciences" double precision null,
  "Biomedical Engineering" double precision null,
  "BioResource and Agricultural Engineering" double precision null,
  "Business Administration" double precision null,
  "Chemistry" double precision null,
  "Child Development" double precision null,
  "City and Regional Planning" double precision null,
  "Civil Engineering" double precision null,
  "Communication Studies" double precision null,
  "Comparative Ethnic Studies" double precision null,
  "Computer Engineering" double precision null,
  "Computer Science" double precision null,
  "Construction Management" double precision null,
  "Dairy Science" double precision null,
  "Economics" double precision null,
  "Electrical Engineering" double precision null,
  "English" double precision null,
  "Environmental Earth and Soil Sciences" double precision null,
  "Environmental Engineering" double precision null,
  "Environmental Management and Protection" double precision null,
  "Food Science" double precision null,
  "Forest and Fire Sciences" double precision null,
  "General Engineering" double precision null,
  "Graphic Communication" double precision null,
  "History" double precision null,
  "Industrial Engineering" double precision null,
  "Industrial Technology and Packaging" double precision null,
  "Interdisciplinary Studies" double precision null,
  "Journalism_1" double precision null,
  "Kinesiology" double precision null,
  "Landscape Architecture" double precision null,
  "Liberal Arts and Engineering Studies" double precision null,
  "Liberal Studies" double precision null,
  "Manufacturing Engineering" double precision null,
  "Marine Sciences" double precision null,
  "Materials Engineering" double precision null,
  "Mathematics" double precision null,
  "Mechanical Engineering" double precision null,
  "Microbiology" double precision null,
  "Music_1" double precision null,
  "Nutrition" double precision null,
  "Philosophy" double precision null,
  "Physics" double precision null,
  "Plant Sciences" double precision null,
  "Political Science" double precision null,
  "Public Health" double precision null,
  "Psychology" double precision null,
  "Recreation, Parks, and Tourism Administration" double precision null,
  "Sociology" double precision null,
  "Software Engineering" double precision null,
  "Spanish" double precision null,
  "Statistics" double precision null,
  "Theatre Arts" double precision null,
  "Wine and Viticulture" double precision null,
  "Description" text not null,
  constraint clubs_stage_raw_pkey primary key ("Description")
) TABLESPACE pg_default;
