CREATE TABLE IF NOT EXISTS users (
    user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -------------------------------------------------
    -- BASIC REQUIRED USER INFO
    -------------------------------------------------
    email text NOT NULL UNIQUE,
    first_name text,
    last_name text,

    -------------------------------------------------
    -- CREATIVE OPTIONAL FIELDS
    -------------------------------------------------
    -- JSON array of recommended clubs:
    -- [{ "club_id": "...", "score": 0.87 }, ...]
    top_clubs jsonb,

    -- Boolean for onboarding progress
    profile_completed boolean DEFAULT false,

    -- Useful demographics (optional)
    class_year int,
    major text,
    pronouns text,

    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),

    -------------------------------------------------
    -- 132 TAG SCORE COLUMNS
    -- Using stable numeric tag indices so tags can change
    -- without modifying the schema itself.
    -------------------------------------------------
    tag_1_score numeric DEFAULT NULL,
    tag_2_score numeric DEFAULT NULL,
    tag_3_score numeric DEFAULT NULL,
    tag_4_score numeric DEFAULT NULL,
    tag_5_score numeric DEFAULT NULL,
    tag_6_score numeric DEFAULT NULL,
    tag_7_score numeric DEFAULT NULL,
    tag_8_score numeric DEFAULT NULL,
    tag_9_score numeric DEFAULT NULL,
    tag_10_score numeric DEFAULT NULL,
    tag_11_score numeric DEFAULT NULL,
    tag_12_score numeric DEFAULT NULL,
    tag_13_score numeric DEFAULT NULL,
    tag_14_score numeric DEFAULT NULL,
    tag_15_score numeric DEFAULT NULL,
    tag_16_score numeric DEFAULT NULL,
    tag_17_score numeric DEFAULT NULL,
    tag_18_score numeric DEFAULT NULL,
    tag_19_score numeric DEFAULT NULL,
    tag_20_score numeric DEFAULT NULL,
    tag_21_score numeric DEFAULT NULL,
    tag_22_score numeric DEFAULT NULL,
    tag_23_score numeric DEFAULT NULL,
    tag_24_score numeric DEFAULT NULL,
    tag_25_score numeric DEFAULT NULL,
    tag_26_score numeric DEFAULT NULL,
    tag_27_score numeric DEFAULT NULL,
    tag_28_score numeric DEFAULT NULL,
    tag_29_score numeric DEFAULT NULL,
    tag_30_score numeric DEFAULT NULL,
    tag_31_score numeric DEFAULT NULL,
    tag_32_score numeric DEFAULT NULL,
    tag_33_score numeric DEFAULT NULL,
    tag_34_score numeric DEFAULT NULL,
    tag_35_score numeric DEFAULT NULL,
    tag_36_score numeric DEFAULT NULL,
    tag_37_score numeric DEFAULT NULL,
    tag_38_score numeric DEFAULT NULL,
    tag_39_score numeric DEFAULT NULL,
    tag_40_score numeric DEFAULT NULL,
    tag_41_score numeric DEFAULT NULL,
    tag_42_score numeric DEFAULT NULL,
    tag_43_score numeric DEFAULT NULL,
    tag_44_score numeric DEFAULT NULL,
    tag_45_score numeric DEFAULT NULL,
    tag_46_score numeric DEFAULT NULL,
    tag_47_score numeric DEFAULT NULL,
    tag_48_score numeric DEFAULT NULL,
    tag_49_score numeric DEFAULT NULL,
    tag_50_score numeric DEFAULT NULL,
    tag_51_score numeric DEFAULT NULL,
    tag_52_score numeric DEFAULT NULL,
    tag_53_score numeric DEFAULT NULL,
    tag_54_score numeric DEFAULT NULL,
    tag_55_score numeric DEFAULT NULL,
    tag_56_score numeric DEFAULT NULL,
    tag_57_score numeric DEFAULT NULL,
    tag_58_score numeric DEFAULT NULL,
    tag_59_score numeric DEFAULT NULL,
    tag_60_score numeric DEFAULT NULL,
    tag_61_score numeric DEFAULT NULL,
    tag_62_score numeric DEFAULT NULL,
    tag_63_score numeric DEFAULT NULL,
    tag_64_score numeric DEFAULT NULL,
    tag_65_score numeric DEFAULT NULL,
    tag_66_score numeric DEFAULT NULL,
    tag_67_score numeric DEFAULT NULL,
    tag_68_score numeric DEFAULT NULL,
    tag_69_score numeric DEFAULT NULL,
    tag_70_score numeric DEFAULT NULL,
    tag_71_score numeric DEFAULT NULL,
    tag_72_score numeric DEFAULT NULL,
    tag_73_score numeric DEFAULT NULL,
    tag_74_score numeric DEFAULT NULL,
    tag_75_score numeric DEFAULT NULL,
    tag_76_score numeric DEFAULT NULL,
    tag_77_score numeric DEFAULT NULL,
    tag_78_score numeric DEFAULT NULL,
    tag_79_score numeric DEFAULT NULL,
    tag_80_score numeric DEFAULT NULL,
    tag_81_score numeric DEFAULT NULL,
    tag_82_score numeric DEFAULT NULL,
    tag_83_score numeric DEFAULT NULL,
    tag_84_score numeric DEFAULT NULL,
    tag_85_score numeric DEFAULT NULL,
    tag_86_score numeric DEFAULT NULL,
    tag_87_score numeric DEFAULT NULL,
    tag_88_score numeric DEFAULT NULL,
    tag_89_score numeric DEFAULT NULL,
    tag_90_score numeric DEFAULT NULL,
    tag_91_score numeric DEFAULT NULL,
    tag_92_score numeric DEFAULT NULL,
    tag_93_score numeric DEFAULT NULL,
    tag_94_score numeric DEFAULT NULL,
    tag_95_score numeric DEFAULT NULL,
    tag_96_score numeric DEFAULT NULL,
    tag_97_score numeric DEFAULT NULL,
    tag_98_score numeric DEFAULT NULL,
    tag_99_score numeric DEFAULT NULL,
    tag_100_score numeric DEFAULT NULL,
    tag_101_score numeric DEFAULT NULL,
    tag_102_score numeric DEFAULT NULL,
    tag_103_score numeric DEFAULT NULL,
    tag_104_score numeric DEFAULT NULL,
    tag_105_score numeric DEFAULT NULL,
    tag_106_score numeric DEFAULT NULL,
    tag_107_score numeric DEFAULT NULL,
    tag_108_score numeric DEFAULT NULL,
    tag_109_score numeric DEFAULT NULL,
    tag_110_score numeric DEFAULT NULL,
    tag_111_score numeric DEFAULT NULL,
    tag_112_score numeric DEFAULT NULL,
    tag_113_score numeric DEFAULT NULL,
    tag_114_score numeric DEFAULT NULL,
    tag_115_score numeric DEFAULT NULL,
    tag_116_score numeric DEFAULT NULL,
    tag_117_score numeric DEFAULT NULL,
    tag_118_score numeric DEFAULT NULL,
    tag_119_score numeric DEFAULT NULL,
    tag_120_score numeric DEFAULT NULL,
    tag_121_score numeric DEFAULT NULL,
    tag_122_score numeric DEFAULT NULL,
    tag_123_score numeric DEFAULT NULL,
    tag_124_score numeric DEFAULT NULL,
    tag_125_score numeric DEFAULT NULL,
    tag_126_score numeric DEFAULT NULL,
    tag_127_score numeric DEFAULT NULL,
    tag_128_score numeric DEFAULT NULL,
    tag_129_score numeric DEFAULT NULL,
    tag_130_score numeric DEFAULT NULL,
    tag_131_score numeric DEFAULT NULL,
    tag_132_score numeric DEFAULT NULL
);
